version: '3'

services:

    nginx:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./nginx/docker.conf:/etc/nginx/conf.d/default.conf:ro
            - ../../:/app
        depends_on:
            - unit

    unit:
        build: ./unit
        ports:
            - 8300:8300
        volumes:
            - ./../../var/log:/var/log
            - ../../:/app