version: '3'

services:

    nginx:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./nginx/docker.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - unit
            - app

    unit:
        build: ./unit
        expose:
            - 8300
        volumes:
            - ./../../var/log:/var/log
            - app-volume:/app

    app:
        build: ../..
        volumes:
            - app-volume:/app

volumes:
    app-volume: