version: '2.3'

services:

    nginx:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./nginx/docker.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php
            - app

    php:
        image: php:7.2-cli
        working_dir: /app
        volumes:
            - app-volume:/app
        expose:
            - 9000
        command:
            - /app/bin/react.php
        scale: 20

    app:
        build: ../..
        volumes:
            - app-volume:/app

volumes:
    app-volume: