version: '3'

services:

    nginx:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./nginx/docker.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - php
            - app

    php:
        build: ./php-cli
        working_dir: /app
        environment:
            TIMEZONE: Europe/Paris
            APP_ENV: prod
            APP_TYPE: react-php
        volumes:
            - app-volume:/app:cached
        expose:
            - 9000
        command:
            - /app/bin/react-worker.php

    app:
        build: ../..
        volumes:
            - app-volume:/app

volumes:
    app-volume: