version: '3'

services:

    nginx:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/docker.conf:/etc/nginx/conf.d/default.conf:ro
            - app-volume:/app:cached
        depends_on:
            - php
            - app

    php:
        build: ./php-cli
        hostname: php
        working_dir: /app
        expose:
            - 9000
        environment:
            TIMEZONE: Europe/Paris
            APP_ENV: prod
            APP_TYPE: php-ppm
        volumes:
            - app-volume:/app:cached
        command:
            - /app/vendor/bin/ppm
            - start
            - --bootstrap=symfony
            - --app-env=prod
            - --logging=0
            - --debug=0
            - --workers=20
            - --max-requests=5000
            - --max-execution-time=5
            - --reload-timeout=30
            - --host=tcp://0.0.0.0
            - --port=9000
    app:
        build: ../..
        volumes:
            - app-volume:/app

volumes:
    app-volume: