version: '3'

services:

    nginx:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/docker.conf:/etc/nginx/conf.d/default.conf:ro
            - app-volume:/app:cached
        depends_on:
            - php
            - app

    php:
        build: ./php-cli
        hostname: php
        working_dir: /app
        expose:
            - 9000
        environment:
            TIMEZONE: Europe/Paris
            APP_ENV: prod
            APP_TYPE: php-ppm
        volumes:
            - app-volume:/app:cached
            - ./php-cli/config.json:/app/config.json
            - ./php-cli/wrapper.sh:/app/wrapper.sh
        command:
            - /app/wrapper.sh
            - /app/vendor/bin/ppm
            - start
            - --config=/app/config.json
    app:
        build: ../..
        volumes:
            - app-volume:/app

volumes:
    app-volume: