version: '3'

services:

    nginx:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./nginx/docker.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php
            - app

    php:
        build: ./php-fpm
        hostname: php
        working_dir: /app
        expose:
            - 9000
        environment:
            TIMEZONE: Europe/Paris
        volumes:
            - app-volume:/app
            - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
            - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    app:
        build: ../..
        volumes:
            - app-volume:/app:cached

volumes:
    app-volume: