version: '3'

services:

    nginx:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./nginx/docker.conf:/etc/nginx/conf.d/default.conf:ro
            - app-volume:/app
        depends_on:
            - php
            - app

    php:
        image: php:7.2-fpm
        hostname: php
        working_dir: /app
        expose:
            - 9000
        volumes:
            - app-volume:/app
            - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf

    app:
        build: ../..
        volumes:
            - app-volume:/app

volumes:
    app-volume: